apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-serving
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf
    spec:
      containers:
      - name: {{ template "fullname" . }}-serving
        image: bitnami/tf-server-slim:0.0.1
        readinessProbe:
          tcpSocket:
            port: {{ .Values.server.port }}
          timeoutSeconds: 1
        volumeMounts:
        - name: seed
          mountPath: "/serving/inception-export"
      volumes:
      - name: seed
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}-seed
