apiVersion: v1
kind: Pod
metadata:
  name: inception
  labels:
    release: inception
spec:
  containers:
  - name: seed
    image: "{{ .Values.image }}"
    command: ["sleep", "3600"]
    volumeMounts:
    - name: seed
      mountPath: /seed
  restartPolicy: Never
  volumes:
  - name: seed
    persistentVolumeClaim:
      claimName: seed
