apiVersion: batch/v1
kind: Job
metadata:
  name: seed-inception
  labels:
    release: inception
spec:
  template:
    metadata:
      name: seed-inception
    spec:
      containers:
      - name: seed
        image: bitnami/minideb-extras:jessie
        command: ["/bin/sh"]
        args: ["-c", "curl -o /seed/inception-v3-2016-03-01.tar.gz http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz && cd /seed/ && tar -xzf inception-v3-2016-03-01.tar.gz && rm inception-v3-2016-03-01.tar.gz"]
        volumeMounts:
        - name: seed
          mountPath: /seed
      restartPolicy: Never
      volumes:
      - name: seed
        persistentVolumeClaim:
          claimName: seed
