apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-service
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.server.port }}
    protocol: TCP
  selector:
    app: tf
